spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/prayz
    username: ${DB_USER:prayz}
    password: ${DB_PASSWORD:prayz}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true