services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:15
    container_name: prayz_db
    restart: always
    environment:
      POSTGRES_DB: prayz
      POSTGRES_USER: prayz
      POSTGRES_PASSWORD: prayz
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Serviço da aplicação Kotlin
  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prayz
      SPRING_DATASOURCE_USERNAME: prayz
      SPRING_DATASOURCE_PASSWORD: prayz
    ports:
      - "8080:8080"

volumes:
  postgres-data: